const { targetName, schemaTargetName } = require('./naming')

module.exports = function generateCMake(hrpc, { schemaTarget } = {}) {
  const target = targetName(hrpc)
  const schema = schemaTarget || schemaTargetName(hrpc)
  return (
    [
      '# This file is autogenerated by hrpc-c',
      '# !!DO NOT EDIT!!',
      '#',
      `# Expects: \`compact\`, \`rpc\`, and \`${schema}\` CMake targets provided by the consumer.`,
      '',
      'cmake_minimum_required(VERSION 4.0)',
      '',
      `project(${target} C)`,
      '',
      `add_library(${target} OBJECT ${target}.c)`,
      '',
      'set_target_properties(',
      `  ${target}`,
      '  PROPERTIES',
      '  C_STANDARD 99',
      ')',
      '',
      `target_include_directories(${target} PUBLIC .)`,
      '',
      `target_link_libraries(${target} PUBLIC compact rpc ${schema})`
    ].join('\n') + '\n'
  )
}
