const errors = require('./errors')
const { toCName, splitFqn, structFromRef, targetName, schemaTargetName } = require('./naming')

const BANNER = ['// This file is autogenerated by hrpc-c', '// !!DO NOT EDIT!!']

// Classify a handler. Only unary is generated in this version; events and
// streams throw so nothing is silently skipped.
function classify(h) {
  const reqStream = h.request.stream === true
  const respStream = h.response && h.response.stream === true
  if (h.request.send === true && !h.response) return 'event'
  if (respStream && !reqStream) return 'response-stream'
  if (reqStream || respStream) return 'stream' // request-stream / duplex: still unsupported
  if (!h.response) {
    throw errors.MISSING_RESPONSE(
      `Handler '${h.name}' has no response; set request.send: true for an event`
    )
  }
  return 'unary'
}

function shortName(h) {
  return toCName(splitFqn(h.name).name)
}

function ns(h) {
  return toCName(splitFqn(h.name).ns)
}

function commandConst(h) {
  return `${ns(h)}_command_${shortName(h)}`
}

function encodeFn(h) {
  return `${ns(h)}_encode_${shortName(h)}`
}

function encodeErrorFn(h) {
  return `${ns(h)}_encode_${shortName(h)}_error`
}

function decodeRespFn(h) {
  return `${ns(h)}_decode_${shortName(h)}_response`
}

function streamOpenFn(h) {
  return `${ns(h)}_encode_${shortName(h)}_open`
}

function streamOpenEchoFn(h) {
  return `${ns(h)}_encode_${shortName(h)}_stream_open`
}

function streamChunkFn(h) {
  return `${ns(h)}_encode_${shortName(h)}_chunk`
}

function streamEndFn(h) {
  return `${ns(h)}_encode_${shortName(h)}_end`
}

function chunkDecodeFn(h) {
  return `${ns(h)}_decode_${shortName(h)}_chunk`
}

function handlerType(h) {
  return `${ns(h)}_on_${shortName(h)}`
}

// Command short-names must be unique across the schema: they key the single
// handler table (on_<shortName>) and dispatch.
function checkUniqueShortNames(hrpc) {
  const seen = new Set()
  for (const h of hrpc.handlers) {
    const s = shortName(h)
    if (seen.has(s)) {
      throw errors.DUPLICATE_COMMAND_NAME(
        `Two handlers map to the C name 'on_${s}'; use distinct command names across the schema`
      )
    }
    seen.add(s)
  }
}

// Schema-independent runtime header, shared by every generated <target>_hrpc.h.
// Header-only (types + enums), so multiple targets in one project never clash.
function sharedHeader() {
  return (
    [
      ...BANNER,
      '#ifndef HRPC_H',
      '#define HRPC_H',
      '',
      '#include <stddef.h>',
      '#include <stdint.h>',
      '#include <utf.h>',
      '',
      '#include "utf/string.h"',
      '',
      '// Error reply / error stream-frame payload. On decode the views point',
      '// into the inbound frame; copy out anything kept past the read loop.',
      'typedef struct {',
      '  utf8_string_view_t message;',
      '  utf8_string_view_t code;',
      '  int64_t status;',
      '} hrpc_error_t;',
      '',
      '// <command>_decode_<name>_response result',
      'enum {',
      '  hrpc_ok = 0,',
      '  hrpc_error_response = 1,',
      '};',
      '',
      '// <target>_dispatch result (>= 0)',
      'enum {',
      '  hrpc_dispatch_reply = 0,',
      '  hrpc_dispatch_no_reply = 1,',
      '  hrpc_dispatch_stream = 2,',
      '};',
      '',
      '// error codes (< 0), distinct from librpc rpc_error / rpc_partial',
      'enum {',
      '  hrpc_err_alloc = -1,',
      '  hrpc_err_decode = -2,',
      '  hrpc_err_unknown = -3,',
      '};',
      '',
      '#endif // HRPC_H'
    ].join('\n') + '\n'
  )
}

function generateHeader(hrpc, schema) {
  const target = targetName(hrpc)
  const guard = target.toUpperCase() + '_H'

  const lines = [
    ...BANNER,
    `#ifndef ${guard}`,
    `#define ${guard}`,
    '',
    `#include "${schema}.h"`,
    '#include "hrpc.h"',
    '#include <rpc.h>',
    '#include <stddef.h>',
    '#include <stdint.h>',
    '',
    'enum {',
    ...hrpc.handlers.map((h) => `  ${commandConst(h)} = ${h.id},`),
    '};',
    ''
  ]

  for (const h of hrpc.handlers) {
    const kind = classify(h)
    const req = structFromRef(h.request.name)

    if (kind === 'event') {
      lines.push(
        `// ${h.name} (event)`,
        'int',
        `${encodeFn(h)} (const ${req}_t *args, uint8_t **out, size_t *out_len);`,
        '',
        `typedef void (*${handlerType(h)}) (void *ctx, const ${req}_t *req);`,
        ''
      )
    } else if (kind === 'response-stream') {
      const chunk = structFromRef(h.response.name)
      lines.push(
        `// ${h.name} (response-stream)`,
        'int',
        `${encodeFn(h)} (uint64_t id, const ${req}_t *args, uint8_t **out, size_t *out_len);`,
        '',
        '// server: open the response stream (rpc_response, stream=open)',
        'int',
        `${streamOpenFn(h)} (uint64_t id, uint8_t **out, size_t *out_len);`,
        '',
        '// client: echo the open back (rpc_stream, stream=response|open) so the peer unblocks',
        'int',
        `${streamOpenEchoFn(h)} (uint64_t id, uint8_t **out, size_t *out_len);`,
        '',
        '// server: one data chunk (rpc_stream, stream=response|data)',
        'int',
        `${streamChunkFn(h)} (uint64_t id, const ${chunk}_t *chunk, uint8_t **out, size_t *out_len);`,
        '',
        '// server: end the stream (rpc_stream, stream=response|end)',
        'int',
        `${streamEndFn(h)} (uint64_t id, uint8_t **out, size_t *out_len);`,
        '',
        '// server: error the stream (rpc_stream, stream=response|close|error)',
        'int',
        `${encodeErrorFn(h)} (uint64_t id, hrpc_error_t error, uint8_t **out, size_t *out_len);`,
        '',
        '// client: decode one data chunk payload. Caller has confirmed msg->stream & rpc_stream_data.',
        'int',
        `${chunkDecodeFn(h)} (const rpc_message_t *msg, ${chunk}_t *out);`,
        '',
        '// Return 0 to accept the stream (dispatch yields hrpc_dispatch_stream); < 0 to reject.',
        '// stream_id == the request id; pass it to the encoders above.',
        `typedef int (*${handlerType(h)}) (void *ctx, const ${req}_t *req, uint64_t stream_id);`,
        ''
      )
    } else {
      const resp = structFromRef(h.response.name)
      lines.push(
        `// ${h.name} (unary)`,
        'int',
        `${encodeFn(h)} (uint64_t id, const ${req}_t *args, uint8_t **out, size_t *out_len);`,
        '',
        'int',
        `${encodeErrorFn(h)} (uint64_t id, hrpc_error_t error, uint8_t **out, size_t *out_len);`,
        '',
        '// Returns hrpc_ok (fills *result), hrpc_error_response (fills *error), or < 0.',
        'int',
        `${decodeRespFn(h)} (const rpc_message_t *msg, ${resp}_t *result, hrpc_error_t *error);`,
        '',
        '// Return hrpc_ok after filling *res, or hrpc_error_response after filling *error.',
        `typedef int (*${handlerType(h)}) (void *ctx, const ${req}_t *req, ${resp}_t *res, hrpc_error_t *error);`,
        ''
      )
    }
  }

  lines.push(
    'typedef struct {',
    '  void *ctx;',
    ...hrpc.handlers.map((h) => `  ${handlerType(h)} on_${shortName(h)};`),
    `} ${target}_handlers_t;`,
    '',
    '// Dispatch one decoded request. Returns hrpc_dispatch_reply (sets',
    '// *reply_out / *reply_len, caller sends then frees), hrpc_dispatch_no_reply,',
    '// hrpc_dispatch_stream, or < 0 (no reply written).',
    'int',
    `${target}_dispatch (const ${target}_handlers_t *handlers, const rpc_message_t *msg, uint8_t **reply_out, size_t *reply_len);`,
    '',
    `#endif // ${guard}`
  )

  return lines.join('\n') + '\n'
}

function generateSource(hrpc, target) {
  const lines = [
    ...BANNER,
    `#include "${target}.h"`,
    '',
    '#include <compact.h>',
    '#include <stdlib.h>',
    '',
    // One framing helper per file: frame + encode an rpc_message into a fresh
    // malloc'd buffer the caller owns.
    'static int',
    `${target}__frame (const rpc_message_t *msg, uint8_t **out, size_t *out_len) {`,
    '  compact_state_t state = {0, 0, NULL};',
    '  int err = rpc_preencode_message(&state, msg);',
    '  if (err < 0) return hrpc_err_decode;',
    '  state.buffer = malloc(state.end);',
    '  if (state.buffer == NULL) return hrpc_err_alloc;',
    '  err = rpc_encode_message(&state, msg);',
    '  if (err < 0) {',
    '    free(state.buffer);',
    '    return hrpc_err_decode;',
    '  }',
    '  *out = state.buffer;',
    '  *out_len = state.end;',
    '  return 0;',
    '}',
    ''
  ]

  for (const h of hrpc.handlers) {
    const kind = classify(h)
    const req = structFromRef(h.request.name)

    if (kind === 'event') {
      // sender: encode a fire-and-forget event (id always 0)
      lines.push(
        'int',
        `${encodeFn(h)} (const ${req}_t *args, uint8_t **out, size_t *out_len) {`,
        '  compact_state_t payload = {0, 0, NULL};',
        `  int err = ${req}_preencode(&payload, args);`,
        '  if (err < 0) return hrpc_err_decode;',
        '  if (payload.end > 0) {',
        '    payload.buffer = malloc(payload.end);',
        '    if (payload.buffer == NULL) return hrpc_err_alloc;',
        `    err = ${req}_encode(&payload, args);`,
        '    if (err < 0) {',
        '      free(payload.buffer);',
        '      return hrpc_err_decode;',
        '    }',
        '  }',
        '',
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_request;',
        '  msg.id = 0;',
        `  msg.command = ${commandConst(h)};`,
        '  msg.stream = 0;',
        '  msg.data = payload.buffer;',
        '  msg.len = payload.end;',
        '',
        `  err = ${target}__frame(&msg, out, out_len);`,
        '  free(payload.buffer);',
        '  return err;',
        '}',
        ''
      )
    } else if (kind === 'response-stream') {
      const chunk = structFromRef(h.response.name)
      lines.push(
        // client: encode the request (type 1, stream 0, args as data)
        'int',
        `${encodeFn(h)} (uint64_t id, const ${req}_t *args, uint8_t **out, size_t *out_len) {`,
        '  compact_state_t payload = {0, 0, NULL};',
        `  int err = ${req}_preencode(&payload, args);`,
        '  if (err < 0) return hrpc_err_decode;',
        '  if (payload.end > 0) {',
        '    payload.buffer = malloc(payload.end);',
        '    if (payload.buffer == NULL) return hrpc_err_alloc;',
        `    err = ${req}_encode(&payload, args);`,
        '    if (err < 0) {',
        '      free(payload.buffer);',
        '      return hrpc_err_decode;',
        '    }',
        '  }',
        '',
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_request;',
        '  msg.id = id;',
        `  msg.command = ${commandConst(h)};`,
        '  msg.stream = 0;',
        '  msg.data = payload.buffer;',
        '  msg.len = payload.end;',
        '',
        `  err = ${target}__frame(&msg, out, out_len);`,
        '  free(payload.buffer);',
        '  return err;',
        '}',
        '',
        // server: open (rpc_response, stream=open, no data)
        'int',
        `${streamOpenFn(h)} (uint64_t id, uint8_t **out, size_t *out_len) {`,
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_response;',
        '  msg.id = id;',
        '  msg.error = false;',
        '  msg.stream = rpc_stream_open;',
        `  return ${target}__frame(&msg, out, out_len);`,
        '}',
        '',
        // client: open echo (rpc_stream, stream=response|open, no data)
        'int',
        `${streamOpenEchoFn(h)} (uint64_t id, uint8_t **out, size_t *out_len) {`,
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_stream;',
        '  msg.id = id;',
        '  msg.stream = rpc_stream_response | rpc_stream_open;',
        `  return ${target}__frame(&msg, out, out_len);`,
        '}',
        '',
        // server: data chunk (rpc_stream, stream=response|data)
        'int',
        `${streamChunkFn(h)} (uint64_t id, const ${chunk}_t *chunk, uint8_t **out, size_t *out_len) {`,
        '  compact_state_t payload = {0, 0, NULL};',
        `  int err = ${chunk}_preencode(&payload, chunk);`,
        '  if (err < 0) return hrpc_err_decode;',
        '  if (payload.end > 0) {',
        '    payload.buffer = malloc(payload.end);',
        '    if (payload.buffer == NULL) return hrpc_err_alloc;',
        `    err = ${chunk}_encode(&payload, chunk);`,
        '    if (err < 0) {',
        '      free(payload.buffer);',
        '      return hrpc_err_decode;',
        '    }',
        '  }',
        '',
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_stream;',
        '  msg.id = id;',
        '  msg.stream = rpc_stream_response | rpc_stream_data;',
        '  msg.data = payload.buffer;',
        '  msg.len = payload.end;',
        '',
        `  err = ${target}__frame(&msg, out, out_len);`,
        '  free(payload.buffer);',
        '  return err;',
        '}',
        '',
        // server: end (rpc_stream, stream=response|end, no data)
        'int',
        `${streamEndFn(h)} (uint64_t id, uint8_t **out, size_t *out_len) {`,
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_stream;',
        '  msg.id = id;',
        '  msg.stream = rpc_stream_response | rpc_stream_end;',
        `  return ${target}__frame(&msg, out, out_len);`,
        '}',
        '',
        // server: error (rpc_stream, stream=response|close|error)
        'int',
        `${encodeErrorFn(h)} (uint64_t id, hrpc_error_t error, uint8_t **out, size_t *out_len) {`,
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_stream;',
        '  msg.id = id;',
        '  msg.stream = rpc_stream_response | rpc_stream_close | rpc_stream_error;',
        '  msg.message = error.message;',
        '  msg.code = error.code;',
        '  msg.status = error.status;',
        `  return ${target}__frame(&msg, out, out_len);`,
        '}',
        '',
        // client: decode one chunk payload
        'int',
        `${chunkDecodeFn(h)} (const rpc_message_t *msg, ${chunk}_t *out) {`,
        '  compact_state_t payload = {0, msg->len, msg->data};',
        `  int err = ${chunk}_decode(&payload, out);`,
        '  if (err < 0) return hrpc_err_decode;',
        '  return 0;',
        '}',
        ''
      )
    } else {
      const resp = structFromRef(h.response.name)

      // client: encode a request
      lines.push(
        'int',
        `${encodeFn(h)} (uint64_t id, const ${req}_t *args, uint8_t **out, size_t *out_len) {`,
        '  compact_state_t payload = {0, 0, NULL};',
        `  int err = ${req}_preencode(&payload, args);`,
        '  if (err < 0) return hrpc_err_decode;',
        '  if (payload.end > 0) {',
        '    payload.buffer = malloc(payload.end);',
        '    if (payload.buffer == NULL) return hrpc_err_alloc;',
        `    err = ${req}_encode(&payload, args);`,
        '    if (err < 0) {',
        '      free(payload.buffer);',
        '      return hrpc_err_decode;',
        '    }',
        '  }',
        '',
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_request;',
        '  msg.id = id;',
        `  msg.command = ${commandConst(h)};`,
        '  msg.stream = 0;',
        '  msg.data = payload.buffer;',
        '  msg.len = payload.end;',
        '',
        `  err = ${target}__frame(&msg, out, out_len);`,
        '  free(payload.buffer);',
        '  return err;',
        '}',
        '',
        // client/server: encode an error reply
        'int',
        `${encodeErrorFn(h)} (uint64_t id, hrpc_error_t error, uint8_t **out, size_t *out_len) {`,
        '  rpc_message_t msg = {0};',
        '  msg.type = rpc_response;',
        '  msg.id = id;',
        '  msg.error = true;',
        '  msg.stream = 0;',
        '  msg.message = error.message;',
        '  msg.code = error.code;',
        '  msg.status = error.status;',
        `  return ${target}__frame(&msg, out, out_len);`,
        '}',
        '',
        // client: decode a typed response or an error reply
        'int',
        `${decodeRespFn(h)} (const rpc_message_t *msg, ${resp}_t *result, hrpc_error_t *error) {`,
        '  if (msg->error) {',
        '    error->message = msg->message;',
        '    error->code = msg->code;',
        '    error->status = msg->status;',
        '    return hrpc_error_response;',
        '  }',
        '  compact_state_t payload = {0, msg->len, msg->data};',
        `  int err = ${resp}_decode(&payload, result);`,
        '  if (err < 0) return hrpc_err_decode;',
        '  return hrpc_ok;',
        '}',
        ''
      )
    }
  }

  // dispatch
  lines.push(
    'int',
    `${target}_dispatch (const ${target}_handlers_t *handlers, const rpc_message_t *msg, uint8_t **reply_out, size_t *reply_len) {`,
    '  switch (msg->command) {'
  )

  for (const h of hrpc.handlers) {
    const kind = classify(h)
    const req = structFromRef(h.request.name)
    const on = `on_${shortName(h)}`

    if (kind === 'event') {
      lines.push(
        `  case ${commandConst(h)}: {`,
        `    if (handlers->${on} == NULL) return hrpc_err_unknown;`,
        `    ${req}_t req = {0};`,
        '    compact_state_t in = {0, msg->len, msg->data};',
        `    if (${req}_decode(&in, &req) < 0) return hrpc_err_decode;`,
        `    handlers->${on}(handlers->ctx, &req);`,
        `    ${req}_destroy(&req);`,
        '    return hrpc_dispatch_no_reply;',
        '  }'
      )
    } else if (kind === 'response-stream') {
      lines.push(
        `  case ${commandConst(h)}: {`,
        `    if (handlers->${on} == NULL) return hrpc_err_unknown;`,
        `    ${req}_t req = {0};`,
        '    compact_state_t in = {0, msg->len, msg->data};',
        `    if (${req}_decode(&in, &req) < 0) return hrpc_err_decode;`,
        `    int r = handlers->${on}(handlers->ctx, &req, msg->id);`,
        `    ${req}_destroy(&req);`,
        '    if (r < 0) return r;',
        '    return hrpc_dispatch_stream;',
        '  }'
      )
    } else {
      const resp = structFromRef(h.response.name)
      lines.push(
        `  case ${commandConst(h)}: {`,
        `    if (handlers->${on} == NULL) return hrpc_err_unknown;`,
        `    ${req}_t req = {0};`,
        '    compact_state_t in = {0, msg->len, msg->data};',
        `    if (${req}_decode(&in, &req) < 0) return hrpc_err_decode;`,
        `    ${resp}_t res = {0};`,
        '    hrpc_error_t error = {0};',
        `    int r = handlers->${on}(handlers->ctx, &req, &res, &error);`,
        `    ${req}_destroy(&req);`,
        '    if (r < 0) {',
        `      ${resp}_destroy(&res);`,
        '      return r;',
        '    }',
        '    if (r == hrpc_error_response) {',
        `      ${resp}_destroy(&res);`,
        '      rpc_message_t reply = {0};',
        '      reply.type = rpc_response;',
        '      reply.id = msg->id;',
        '      reply.error = true;',
        '      reply.stream = 0;',
        '      reply.message = error.message;',
        '      reply.code = error.code;',
        '      reply.status = error.status;',
        `      r = ${target}__frame(&reply, reply_out, reply_len);`,
        '      return r < 0 ? r : hrpc_dispatch_reply;',
        '    }',
        '    compact_state_t payload = {0, 0, NULL};',
        `    if (${resp}_preencode(&payload, &res) < 0) {`,
        `      ${resp}_destroy(&res);`,
        '      return hrpc_err_decode;',
        '    }',
        '    if (payload.end > 0) {',
        '      payload.buffer = malloc(payload.end);',
        '      if (payload.buffer == NULL) {',
        `        ${resp}_destroy(&res);`,
        '        return hrpc_err_alloc;',
        '      }',
        `      if (${resp}_encode(&payload, &res) < 0) {`,
        '        free(payload.buffer);',
        `        ${resp}_destroy(&res);`,
        '        return hrpc_err_decode;',
        '      }',
        '    }',
        `    ${resp}_destroy(&res);`,
        '    rpc_message_t reply = {0};',
        '    reply.type = rpc_response;',
        '    reply.id = msg->id;',
        '    reply.error = false;',
        '    reply.stream = 0;',
        '    reply.data = payload.buffer;',
        '    reply.len = payload.end;',
        `    r = ${target}__frame(&reply, reply_out, reply_len);`,
        '    free(payload.buffer);',
        '    return r < 0 ? r : hrpc_dispatch_reply;',
        '  }'
      )
    }
  }

  lines.push('  default:', '    return hrpc_err_unknown;', '  }', '}')

  return lines.join('\n') + '\n'
}

// Returns { shared, header, source }: the shared hrpc.h, the per-target header,
// and the per-target source.
function generateC(hrpc, { schemaTarget } = {}) {
  checkUniqueShortNames(hrpc)
  for (const h of hrpc.handlers) {
    const kind = classify(h)
    if (kind !== 'unary' && kind !== 'event' && kind !== 'response-stream') {
      throw errors.UNSUPPORTED_HANDLER(
        `Handler '${h.name}' is a ${kind} handler; only unary, event, and response-stream are supported in this version`
      )
    }
  }

  const target = targetName(hrpc)
  const schema = schemaTarget || schemaTargetName(hrpc)

  return {
    shared: sharedHeader(),
    header: generateHeader(hrpc, schema),
    source: generateSource(hrpc, target)
  }
}

module.exports = generateC
module.exports.targetName = targetName
module.exports.schemaTargetName = schemaTargetName
